#!/bin/sh
#
# Homebrew
#
# This installs some of the common dependencies needed (or at least desired)
# using Homebrew.

# Check for Homebrew
if test ! $(which brew)
then
  ruby -e "$(curl -fsSkL raw.github.com/mxcl/homebrew/go)"
  exit
else
  echo "  + Homebrew found."
fi

# Install grc and coreutils
brew install grc coreutils

brew install tree bash-completion sshuttle wget hub
